footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.05

robot_base_frame: footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 4.0 #The "obstacle_range" parameter determines the maximum range sensor reading that will result in an obstacle being put into the costmap
raytrace_range: 5.0 #The "raytrace_range" parameter determines the range to which we will raytrace freespace given a sensor reading. 

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_sensor
    #laser: {data_type: LaserScan, clearing: true, marking: true, topic: ugvbot/scan, inf_is_valid: true}
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: ugvbot/scan, marking: true, clearing: false}
inflation:
    inflation_radius: 0.3
